// <auto-generated />
namespace K_12.WEB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class DisplayName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DisplayName));
        
        string IMigrationMetadata.Id
        {
            get { return "201703222259013_DisplayName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
