//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K_12.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity : BaseEntity 
    {
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Time_Given { get; set; }
        public Nullable<int> section_id { get; set; }
        public Nullable<int> subject_id { get; set; }
    
        public virtual Class Class { get; set; }
    }
}
