//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K_12.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application : BaseEntity 
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Application()
        {
            this.Documents = new HashSet<Document>();
        }
    
        public Nullable<int> applicant_id { get; set; }
        public Nullable<int> student_id { get; set; }
        public string app_status { get; set; }
        public Nullable<System.DateTime> application_date { get; set; }
        public Nullable<int> grade_applying_id { get; set; }
        public string Remark { get; set; }
    
        public virtual Applicant Applicant { get; set; }
        public virtual Grade_Info Grade_Info { get; set; }
        public virtual Student Student { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Document> Documents { get; set; }
    }
}
