//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K_12.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document : BaseEntity 
    {
        public string Doc_path { get; set; }
        public Nullable<bool> IsVerified { get; set; }
        public string type { get; set; }
        public Nullable<int> Application_id { get; set; }
    
        public virtual Application Application { get; set; }
    }
}
