//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K_12.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grade_Info : BaseEntity
    {
        public string Grade { get; set; }
        public Nullable<int> Fee { get; set; }
        public string Curriculum { get; set; }
        public string Other_info { get; set; }
        public Nullable<int> Capacity { get; set; }
        public Nullable<int> Current_students { get; set; }
    }
}
