//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K_12.Entity
{
    using System;
    using System.Collections.Generic;
    
    public abstract partial class Person : BaseEntity 
    {
        public string FName { get; set; }
        public string LName { get; set; }
        public string MName { get; set; }
        public string Gender { get; set; }
    }
}
