//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K_12.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration : BaseEntity 
    {
        public Nullable<int> student_id { get; set; }
        public Nullable<System.DateTime> reg_date { get; set; }
        public Nullable<int> Year { get; set; }
        public string Remark { get; set; }
        public string reg_status { get; set; }
        public Nullable<int> grade_id { get; set; }
    
        public virtual Grade_Info Grade_Info { get; set; }
        public virtual Student Student { get; set; }
    }
}
