//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K_12.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff : Person 
    {
        public Nullable<System.DateTime> DOB { get; set; }
        public string Status { get; set; }
        public Nullable<int> address_id { get; set; }
        public string StaffType { get; set; }
        public string user_id { get; set; }
        public Nullable<System.DateTime> Claim_Date { get; set; }
    
        public virtual Address Address { get; set; }
    }
}
